<div class="alert alert-block alert-success">
    <b><center>Tensorflow 2</center></b>
    <b><center>Tensorflow 2기본 사용법</center></b>
</div>

# Configure Learning Environment

In [1]:
# !pip install git+https://github.com/nockchun/rspy --force
import rspy as rsp
rsp.setSystemWarning(off=True)

In [2]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import utils, layers, models, losses

In [3]:
np.set_printoptions(linewidth=200, precision=2)
sns.set_style("whitegrid")
tf.__version__

'2.0.0'

# With Numpy

In [4]:
np2d = np.random.random([4, 5])
np3d = np.random.random([3, 4, 5])
np2d.shape, np3d.shape

((4, 5), (3, 4, 5))

In [5]:
tf2d = tf.convert_to_tensor(np2d)
tf3d = tf.Variable(np3d)
tf2d.shape, tf3d.shape

(TensorShape([4, 5]), TensorShape([3, 4, 5]))

In [8]:
np.add(tf2d, 1)

array([[1.31, 1.19, 1.64, 1.14, 1.7 ],
       [1.96, 1.87, 1.11, 1.85, 1.7 ],
       [1.52, 1.31, 1.88, 1.37, 1.91],
       [1.47, 1.14, 1.45, 1.67, 1.68]])

In [9]:
tf.add(np2d, 1)

<tf.Tensor: id=13, shape=(4, 5), dtype=float64, numpy=
array([[1.31, 1.19, 1.64, 1.14, 1.7 ],
       [1.96, 1.87, 1.11, 1.85, 1.7 ],
       [1.52, 1.31, 1.88, 1.37, 1.91],
       [1.47, 1.14, 1.45, 1.67, 1.68]])>

In [18]:
rsp.showMulti(tf2d, tf2d.numpy())

GridspecLayout(children=(Output(layout=Layout(grid_area='widget001')), Output(layout=Layout(grid_area='widget0…

In [19]:
np2dMul = np.random.random([5, 4])
tf2dMul = tf.convert_to_tensor(np2dMul)

In [20]:
tf.matmul(np2d, np2dMul)

<tf.Tensor: id=21, shape=(4, 4), dtype=float64, numpy=
array([[0.92, 0.61, 1.37, 0.94],
       [2.44, 0.8 , 2.43, 1.95],
       [1.52, 0.86, 2.03, 1.42],
       [1.41, 0.56, 1.51, 1.08]])>

In [21]:
np.dot(tf2d, tf2dMul)

array([[0.92, 0.61, 1.37, 0.94],
       [2.44, 0.8 , 2.43, 1.95],
       [1.52, 0.86, 2.03, 1.42],
       [1.41, 0.56, 1.51, 1.08]])

In [22]:
np.dot(tf2d, np2dMul)

array([[0.92, 0.61, 1.37, 0.94],
       [2.44, 0.8 , 2.43, 1.95],
       [1.52, 0.86, 2.03, 1.42],
       [1.41, 0.56, 1.51, 1.08]])