<div class="alert alert-block alert-success">
    <b><center>Tensorflow 2</center></b>
    <b><center>Tensorflow 2기본 사용법</center></b>
</div>

# Configure Learning Environment

In [2]:
# !pip install git+https://github.com/nockchun/rspy --force
import rspy as rsp
rsp.setSystemWarning(off=True)

In [3]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import utils, layers, models, losses

In [4]:
np.set_printoptions(linewidth=200, precision=2)
sns.set_style("whitegrid")
tf.__version__

'2.0.0'

# Basic

In [5]:
data = np.random.random([10, 5])

In [8]:
ds = tf.data.Dataset.from_tensor_slices(data)

In [18]:
def myMap(val):
    return val + 1

In [19]:
for item in ds:
    print(item)

tf.Tensor([0.41 0.41 0.15 0.48 0.17], shape=(5,), dtype=float64)
tf.Tensor([0.88 0.31 0.16 0.09 0.15], shape=(5,), dtype=float64)
tf.Tensor([0.49 0.22 0.51 0.98 0.21], shape=(5,), dtype=float64)
tf.Tensor([0.86 0.3  0.45 0.5  0.18], shape=(5,), dtype=float64)
tf.Tensor([0.53 0.36 0.07 0.53 0.82], shape=(5,), dtype=float64)
tf.Tensor([0.76 0.26 0.77 0.65 0.1 ], shape=(5,), dtype=float64)
tf.Tensor([7.22e-01 1.77e-01 1.98e-04 1.97e-01 6.05e-01], shape=(5,), dtype=float64)
tf.Tensor([0.84 0.43 0.6  0.82 0.27], shape=(5,), dtype=float64)
tf.Tensor([0.65 0.15 0.25 0.02 0.84], shape=(5,), dtype=float64)
tf.Tensor([0.25 0.65 0.97 0.97 0.87], shape=(5,), dtype=float64)


In [94]:
for item in ds.map(myMap):
    print(item)

tf.Tensor([1.41 1.41 1.15 1.48 1.17], shape=(5,), dtype=float64)
tf.Tensor([1.88 1.31 1.16 1.09 1.15], shape=(5,), dtype=float64)
tf.Tensor([1.49 1.22 1.51 1.98 1.21], shape=(5,), dtype=float64)
tf.Tensor([1.86 1.3  1.45 1.5  1.18], shape=(5,), dtype=float64)
tf.Tensor([1.53 1.36 1.07 1.53 1.82], shape=(5,), dtype=float64)
tf.Tensor([1.76 1.26 1.77 1.65 1.1 ], shape=(5,), dtype=float64)
tf.Tensor([1.72 1.18 1.   1.2  1.6 ], shape=(5,), dtype=float64)
tf.Tensor([1.84 1.43 1.6  1.82 1.27], shape=(5,), dtype=float64)
tf.Tensor([1.65 1.15 1.25 1.02 1.84], shape=(5,), dtype=float64)
tf.Tensor([1.25 1.65 1.97 1.97 1.87], shape=(5,), dtype=float64)


In [111]:
for item in ds.shuffle(10):
    print(item)

tf.Tensor([0.88 0.31 0.16 0.09 0.15], shape=(5,), dtype=float64)
tf.Tensor([7.22e-01 1.77e-01 1.98e-04 1.97e-01 6.05e-01], shape=(5,), dtype=float64)
tf.Tensor([0.41 0.41 0.15 0.48 0.17], shape=(5,), dtype=float64)
tf.Tensor([0.76 0.26 0.77 0.65 0.1 ], shape=(5,), dtype=float64)
tf.Tensor([0.86 0.3  0.45 0.5  0.18], shape=(5,), dtype=float64)
tf.Tensor([0.25 0.65 0.97 0.97 0.87], shape=(5,), dtype=float64)
tf.Tensor([0.53 0.36 0.07 0.53 0.82], shape=(5,), dtype=float64)
tf.Tensor([0.65 0.15 0.25 0.02 0.84], shape=(5,), dtype=float64)
tf.Tensor([0.49 0.22 0.51 0.98 0.21], shape=(5,), dtype=float64)
tf.Tensor([0.84 0.43 0.6  0.82 0.27], shape=(5,), dtype=float64)


In [113]:
for item in ds.batch(2):
    print(item)

tf.Tensor(
[[0.41 0.41 0.15 0.48 0.17]
 [0.88 0.31 0.16 0.09 0.15]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[0.49 0.22 0.51 0.98 0.21]
 [0.86 0.3  0.45 0.5  0.18]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[0.53 0.36 0.07 0.53 0.82]
 [0.76 0.26 0.77 0.65 0.1 ]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[7.22e-01 1.77e-01 1.98e-04 1.97e-01 6.05e-01]
 [8.44e-01 4.29e-01 6.04e-01 8.22e-01 2.72e-01]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[0.65 0.15 0.25 0.02 0.84]
 [0.25 0.65 0.97 0.97 0.87]], shape=(2, 5), dtype=float64)


In [137]:
feed = ds.map(myMap).shuffle(10).batch(2)

In [140]:
for _ in range(2):
    for item in feed:
        print(item)
    print()

tf.Tensor(
[[1.49 1.22 1.51 1.98 1.21]
 [1.41 1.41 1.15 1.48 1.17]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.86 1.3  1.45 1.5  1.18]
 [1.72 1.18 1.   1.2  1.6 ]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.76 1.26 1.77 1.65 1.1 ]
 [1.84 1.43 1.6  1.82 1.27]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.88 1.31 1.16 1.09 1.15]
 [1.65 1.15 1.25 1.02 1.84]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.53 1.36 1.07 1.53 1.82]
 [1.25 1.65 1.97 1.97 1.87]], shape=(2, 5), dtype=float64)

tf.Tensor(
[[1.53 1.36 1.07 1.53 1.82]
 [1.25 1.65 1.97 1.97 1.87]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.84 1.43 1.6  1.82 1.27]
 [1.88 1.31 1.16 1.09 1.15]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.72 1.18 1.   1.2  1.6 ]
 [1.86 1.3  1.45 1.5  1.18]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.76 1.26 1.77 1.65 1.1 ]
 [1.41 1.41 1.15 1.48 1.17]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.65 1.15 1.25 1.02 1.84]
 [1.49 1.22 1.51 1.98 1.21]], shape=(2, 5), dtype=float64)



In [141]:
for _ in range(2):
    for item in feed.take(2):
        print(item)
    print()

tf.Tensor(
[[1.41 1.41 1.15 1.48 1.17]
 [1.25 1.65 1.97 1.97 1.87]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.72 1.18 1.   1.2  1.6 ]
 [1.88 1.31 1.16 1.09 1.15]], shape=(2, 5), dtype=float64)

tf.Tensor(
[[1.76 1.26 1.77 1.65 1.1 ]
 [1.25 1.65 1.97 1.97 1.87]], shape=(2, 5), dtype=float64)
tf.Tensor(
[[1.88 1.31 1.16 1.09 1.15]
 [1.86 1.3  1.45 1.5  1.18]], shape=(2, 5), dtype=float64)

