<div class="alert alert-block alert-success">
    <b><center>TENSORFLOW 2 LIBRARY</center></b>
    <b><center>Tensorflow 2 사용하기 01</center></b>
</div>

# Configure Learning Environment

In [1]:
# !pip install git+https://github.com/nockchun/rspy --force
import rspy as rsp
rsp.setSystemWarning(off=True)

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
np.set_printoptions(linewidth=200, precision=2)
print("버전: ", tf.__version__)
print("즉시 실행 모드: ", tf.executing_eagerly())
print("GPU: ", "사용 가능" if tf.test.is_gpu_available() else "사용 불가능")
print("GPU Device: ", tf.config.experimental.get_visible_devices("GPU"))

버전:  2.0.0
즉시 실행 모드:  True
GPU:  사용 가능
GPU Device:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# Variables

In [4]:
c1 = tf.constant("Hello Tensorflow!")
c1

<tf.Tensor: id=0, shape=(), dtype=string, numpy=b'Hello Tensorflow!'>

In [5]:
c2 = tf.constant(1.5)
c1.numpy(), c2.numpy()

(b'Hello Tensorflow!', 1.5)

In [6]:
# initialization 필요 없음.
v1 = tf.Variable("Hello Tensorflow!")
v2 = tf.Variable(1.5)
c1.numpy(), c2.numpy()

(b'Hello Tensorflow!', 1.5)

In [7]:
# assign to variables
v1.assign("changed"), v2.assign_add(3)

(<tf.Variable 'UnreadVariable' shape=() dtype=string, numpy=b'changed'>,
 <tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=4.5>)

# Basic Calulation

In [8]:
v3 = tf.Variable( np.random.normal(size=[2, 2]) )
v4 = tf.Variable( np.random.normal(size=[2, 2]) )
v3, v4

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
 array([[-0.03, -0.8 ],
        [ 1.64, -0.88]])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
 array([[ 0.07, -0.03],
        [ 1.34, -2.48]])>)

In [9]:
tf.square(v3)

<tf.Tensor: id=40, shape=(2, 2), dtype=float64, numpy=
array([[1.09e-03, 6.38e-01],
       [2.68e+00, 7.75e-01]])>

In [10]:
v3 + v4, tf.add(v3, v4)

(<tf.Tensor: id=43, shape=(2, 2), dtype=float64, numpy=
 array([[ 0.04, -0.83],
        [ 2.97, -3.36]])>,
 <tf.Tensor: id=46, shape=(2, 2), dtype=float64, numpy=
 array([[ 0.04, -0.83],
        [ 2.97, -3.36]])>)

In [11]:
tf.matmul(v3, v4)

<tf.Tensor: id=49, shape=(2, 2), dtype=float64, numpy=
array([[-1.07,  1.98],
       [-1.06,  2.14]])>

# GradientTape

In [25]:
v5 = tf.Variable( np.ones([2, 2]) )
v5.numpy()

array([[1., 1.],
       [1., 1.]])

In [27]:
tape = tf.GradientTape()


In [31]:
x = tf.ones((2, 2))
print(x)

with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    print(y)
    z = tf.multiply(y, y)

# 입력 텐서 x에 대한 z의 도함수
dz_dx = t.gradient(z, x)
for i in [0, 1]:
    for j in [0, 1]:
        assert dz_dx[i][j].numpy() == 8.0

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [21]:
with tf.GradientTape() as tape:
    eq = tf.sqrt(tf.square(v3) + tf.square(v4))
    dEq_dv3 = tape.gradient(eq, v3)
    rsp.showMulti(eq.numpy(), v3.numpy(), dEq_dv3.numpy() )

GridspecLayout(children=(Output(layout=Layout(grid_area='widget001')), Output(layout=Layout(grid_area='widget0…