In [1]:
import torch

# Tensor

## 산술연산

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([1, 1, 1])

print("[+] Addition")
print(f"a + b + c = {a + b + c}")
print(f"torch.add(a, b).add(c) = {torch.add(a, b).add(c)}")

print("\n[+] Subtraction")
print(f"a - b = {a - b}")
print(f"torch.sub(a, b) = {torch.sub(a, b)}")

print("\n[+] Element-wise Multiplication")
print(f"a * b = {a * b}")
print(f"torch.mul(a, b) = {torch.mul(a, b)}")

print("\n[+] Element-wise Division")
print(f"a / b = {a / b}")
print(f"torch.div(a, b) = {torch.div(a, b)}")

[+] Addition
a + b + c = tensor([ 6,  8, 10])
torch.add(a, b).add(c) = tensor([ 6,  8, 10])

[+] Subtraction
a - b = tensor([-3, -3, -3])
torch.sub(a, b) = tensor([-3, -3, -3])

[+] Element-wise Multiplication
a * b = tensor([ 4, 10, 18])
torch.mul(a, b) = tensor([ 4, 10, 18])

[+] Element-wise Division
a / b = tensor([0.2500, 0.4000, 0.5000])
torch.div(a, b) = tensor([0.2500, 0.4000, 0.5000])


In [10]:
# In-place operations (modifies the tensor)
d = torch.tensor([1, 2, 3])
print(f"[+] Original d = {d}")

d.add_(b)  # underscore suffix : in-place operations
print(f"[+] After d.add_(b), d = {d}")

[+] Original d = tensor([1, 2, 3])
[+] After d.add_(b), d = tensor([5, 7, 9])


## Matrix 연산

In [12]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(f"[+] Matrix a:\n{a}")
print(f"[+] Matrix b:\n{b}")

# Matrix multiplication
print(f"\nMatrix multiplication (torch.matmul(a, b)):\n{torch.matmul(a, b)}")
print(f"Matrix multiplication (a @ b):\n{a @ b}")

[+] Matrix a:
tensor([[1, 2],
        [3, 4]])
[+] Matrix b:
tensor([[5, 6],
        [7, 8]])

Matrix multiplication (torch.matmul(a, b)):
tensor([[19, 22],
        [43, 50]])
Matrix multiplication (a @ b):
tensor([[19, 22],
        [43, 50]])


In [13]:
# Transpose
print(f"\nTranspose of a:\n{a.t()}\n{a.T}")


Transpose of a:
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])


# PyTorch 학습 과정 개념

## 순전파(Forward)

In [14]:
# 1) 예제 데이터 (x: 입력)
x = torch.tensor([[1.0],
                  [2.0],
                  [3.0]])  # (3, 1) : 샘플 3개, 특징 1개

In [15]:
# 2) 가중치와 편향 (여기서는 그냥 수동으로 줌)
w = torch.tensor([[2.0]])  # (1, 1)
b = torch.tensor([1.0])    # (1,)

In [16]:
# 3) 순전파: y_pred = x @ w + b
y_pred = x @ w + b  # 또는 torch.matmul(x, w) + b

In [17]:
print("x shape:", x.shape)
print("y_pred shape:", y_pred.shape)
print("y_pred:\n", y_pred)

x shape: torch.Size([3, 1])
y_pred shape: torch.Size([3, 1])
y_pred:
 tensor([[3.],
        [5.],
        [7.]])


## 손실 계산(MSE Loss)

In [24]:
# 1) 입력, 정답, 모델 파라미터
x = torch.tensor([[1.0],
                  [2.0],
                  [3.0]])
y_true = torch.tensor([[3.0],
                       [5.0],
                       [7.0]])  # 실제로 y = 2x + 1

In [25]:
# 2) 가중치와 편향 (일부러 틀린 값)
w = torch.tensor([[1.5]])
b = torch.tensor([0.5])

In [26]:
# 3) 순전파
y_pred = x @ w + b

In [27]:
# 4) 손실 계산 (MSE)
loss = torch.mean((y_pred - y_true) ** 2)

In [28]:
print("y_pred:\n", y_pred)
print("y_true:\n", y_true)
print("loss:", loss.item())

y_pred:
 tensor([[2.0000],
        [3.5000],
        [5.0000]])
y_true:
 tensor([[3.],
        [5.],
        [7.]])
loss: 2.4166667461395264


## 역전파(Backpropagation)

In [29]:
# 1) 데이터
x = torch.tensor([[1.0],
                  [2.0],
                  [3.0]])

y_true = torch.tensor([[3.0],
                       [5.0],
                       [7.0]])

In [30]:
# 2) 파라미터: requires_grad=True 로 설정
w = torch.tensor([[1.5]], requires_grad=True)
b = torch.tensor([0.5],  requires_grad=True)

In [31]:
# 3) 순전파
y_pred = x @ w + b
loss = torch.mean((y_pred - y_true) ** 2)

In [32]:
print("초기 loss:", loss.item())

초기 loss: 2.4166667461395264


In [33]:
# 4) 역전파
loss.backward()  # d(loss)/dw, d(loss)/db를 계산

In [36]:
print("w.grad:", w.grad)
print("b.grad:", b.grad) # 손실을 줄이기 위해 w, b를 어느 방향으로/얼마나 바꿀지를 알려주는 정보

w.grad: tensor([[-6.6667]])
b.grad: tensor([-3.])


## 가중치 업데이트(Weight Update)

In [82]:
x = torch.tensor([[1.0],
                  [2.0],
                  [3.0]])

y_true = torch.tensor([[3.0],
                       [5.0],
                       [7.0]])

In [83]:
# 학습 가능한 파라미터
w = torch.tensor([[1.5]], requires_grad=True)
b = torch.tensor([0.5],  requires_grad=True)

In [84]:
learning_rate = 0.1

In [85]:
for step in range(20):
    # 1) 순전파
    y_pred = x @ w + b

    # 2) 손실계산
    loss = torch.mean((y_pred - y_true) ** 2)

    # 기존 gradient 초기화 : PyTorch는 backward() 호출시 gradient를 누적함. step별 gradient 쓰기 위한 방법.
    if w.grad is not None:
        w.grad.zero_()
        b.grad.zero_()

    # 3) 역전파
    loss.backward()

    # 4) 가중치 업데이트 (no_grad 블록 안에서)
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    print(f"step {step+1:2d} | loss = {loss.item():.4f} | w = {w.item():.4f}, b = {b.item():.4f}")

step  1 | loss = 2.4167 | w = 2.1667, b = 0.8000
step  2 | loss = 0.0363 | w = 2.0911, b = 0.7733
step  3 | loss = 0.0075 | w = 2.0967, b = 0.7822
step  4 | loss = 0.0068 | w = 2.0936, b = 0.7871
step  5 | loss = 0.0065 | w = 2.0914, b = 0.7922
step  6 | loss = 0.0062 | w = 2.0892, b = 0.7972
step  7 | loss = 0.0059 | w = 2.0871, b = 0.8021
step  8 | loss = 0.0056 | w = 2.0850, b = 0.8069
step  9 | loss = 0.0054 | w = 2.0829, b = 0.8115
step 10 | loss = 0.0051 | w = 2.0809, b = 0.8160
step 11 | loss = 0.0049 | w = 2.0790, b = 0.8205
step 12 | loss = 0.0046 | w = 2.0771, b = 0.8248
step 13 | loss = 0.0044 | w = 2.0752, b = 0.8290
step 14 | loss = 0.0042 | w = 2.0734, b = 0.8331
step 15 | loss = 0.0040 | w = 2.0717, b = 0.8371
step 16 | loss = 0.0038 | w = 2.0699, b = 0.8410
step 17 | loss = 0.0036 | w = 2.0683, b = 0.8448
step 18 | loss = 0.0035 | w = 2.0666, b = 0.8486
step 19 | loss = 0.0033 | w = 2.0650, b = 0.8522
step 20 | loss = 0.0031 | w = 2.0634, b = 0.8558


# 미니 학습 예제 : Optimizer(SGD/Adam) 사용

In [98]:
x = torch.tensor([[1.0],
                  [2.0],
                  [3.0]])

y_true = torch.tensor([[3.0],
                       [5.0],
                       [7.0]])

In [102]:
# 파라미터
w = torch.tensor([[1.5]], requires_grad=True)
b = torch.tensor([0.5],  requires_grad=True)

In [103]:
# 파라미터를 묶어서 optimizer에 넘기기
optimizer = torch.optim.SGD([w, b], lr=0.1)

In [104]:
for step in range(20):
    # 1) 순전파
    y_pred = x @ w + b
    loss = torch.mean((y_pred - y_true) ** 2)

    # 2) gradient 초기화
    optimizer.zero_grad()

    # 3) 역전파
    loss.backward()

    # 4) optimizer가 내부적으로 w, b 업데이트
    optimizer.step()

    print(f"step {step+1:2d} | loss = {loss.item():.4f} | w = {w.item():.4f}, b = {b.item():.4f}")

step  1 | loss = 2.4167 | w = 2.1667, b = 0.8000
step  2 | loss = 0.0363 | w = 2.0911, b = 0.7733
step  3 | loss = 0.0075 | w = 2.0967, b = 0.7822
step  4 | loss = 0.0068 | w = 2.0936, b = 0.7871
step  5 | loss = 0.0065 | w = 2.0914, b = 0.7922
step  6 | loss = 0.0062 | w = 2.0892, b = 0.7972
step  7 | loss = 0.0059 | w = 2.0871, b = 0.8021
step  8 | loss = 0.0056 | w = 2.0850, b = 0.8069
step  9 | loss = 0.0054 | w = 2.0829, b = 0.8115
step 10 | loss = 0.0051 | w = 2.0809, b = 0.8160
step 11 | loss = 0.0049 | w = 2.0790, b = 0.8205
step 12 | loss = 0.0046 | w = 2.0771, b = 0.8248
step 13 | loss = 0.0044 | w = 2.0752, b = 0.8290
step 14 | loss = 0.0042 | w = 2.0734, b = 0.8331
step 15 | loss = 0.0040 | w = 2.0717, b = 0.8371
step 16 | loss = 0.0038 | w = 2.0699, b = 0.8410
step 17 | loss = 0.0036 | w = 2.0683, b = 0.8448
step 18 | loss = 0.0035 | w = 2.0666, b = 0.8486
step 19 | loss = 0.0033 | w = 2.0650, b = 0.8522
step 20 | loss = 0.0031 | w = 2.0634, b = 0.8558
